### PR TITLE
Add Zotero 7 Support (Not backwards Compatible)

### PR DESCRIPTION
**Pull request by u-ashish**
## Context

Finally fixes https://github.com/scitedotai/scite-zotero-plugin/issues/55

Update the scite plugin to support Zotero 7. You can find the official Zotero notes for developers [here](https://www.zotero.org/support/dev/zotero_7_for_developers).

## Changelog
- Refactor to use [zotero-plugin](https://github.com/retorquere/zotero-plugin) to manage releases
- Re-write the plugin for bootstrapped mode only (I removed overlay support which was used in Zotero 5 / 6).
- Set the new release to a new major version

## Testing XPI

Take this file, extract the `.xpi` file and install it as a plugin in Zotero (assuming you are using Zotero 7).

[scite-zotero-plugin-2.0.0.ashish.rp-prod-lap-242.local.xpi.zip](https://github.com/user-attachments/files/16602546/scite-zotero-plugin-2.0.0.ashish.rp-prod-lap-242.local.xpi.zip)

## Local Code Notes

- Assumes latest `npm@10.8.1` / `node@20.16.0`
- You can do `npm run build` locally to check the `build/` and `xpi/` output to see what the plugin structure looks like after it goes through `esbuild`
- Start in `bootstrap.ts` -> We load `lib.ts` which is what initializes `Zotero.Scite` and then registers the scite specific columns, data retrieval, and rendering.

## Screenshots

Screen Shot 2024-08-12 at 6 38 48 PM

Screen Shot 2024-08-12 at 6 38 54 PM

Screen Shot 2024-08-13 at 11 23 01 AM

## TODO
- [x] Get review from @domenicrosati
- [x] See if there's any functionality from before that we're missing
- [ ] Update deploy scripts
- [x] Decide if we need to keep a legacy branch for Zotero 6
- [x] Make sure bad things don't happen for legacy Zotero users with the update files
- [x] Update README

### CODE REVIEW

**Comment by llity** [comment]
Can it be displayed in the sidebar? Thank you.

**Comment by u-ashish** [comment]
> Can it be displayed in the sidebar? Thank you.

Ask and you shall receive :)

Screen Shot 2024-08-13 at 11 23 01 AM

**Comment by u-ashish** [comment]
> Thanks for the test xpi! I installed it and it seems to display scite columns and data. I haven't checked the reported supporting/contrasting etc. values on scite web site yet. Issue - activating the plugin changes the column width adjustment in Zotero. Once the plugin is enabled, it changes the adjustment behaviour so that other columns in the main display window change size, some of which, e.g. Title and Edition columns can't be modified. Disabling the plugin allows the original column size behaviour to return.
> 
> Screen recording is below:
> Screen.Recording.2024-08-13.094443_2.mp4

I updated the PR with a new test XPI, can you see if that helped? Your video doesn't load for me. I'm testing on my monitor which is wide so that might be why I didn't notice anything off

**Comment by u-ashish** [comment]
We tested this locally. I am going to merge and then try out a release!

**Comment by jlu511** [comment]
hi, thanks for amazing work. Does this plugin surpport locale language? or is it possible to provide a template for localizing languages.

**Comment by jlu511** [comment]
> We tested this locally. I am going to merge and then try out a release!

hi, thanks for amazing work. Does this plugin surpport locale language? or is it possible to provide a template for localizing languages.

**Comment by JacobKorir** [comment]
I downloaded the Scite plugin (V2.0.2) using Chrome and I'm using Zotero 7.0.11. The plugin is still not working. Is there any solution.

**Pull request merged**
