### PR TITLE
Adjust scite plugin for the Zotero HTML tree

### PR DESCRIPTION
**Pull request by adomasven**
Hi Scite developers,

We at Zotero have recently merged a change which replaces the XUL tree with a HTML-JS-React based version of it. See https://github.com/zotero/zotero/pull/2029. We are doing this as part of our move away from deprecated Mozilla technologies and also to allow us to do more awesome things in our item and collection views.

We want to make sure our plugin developers that enhance the item tree are not left behind in the transition. I was looking for a simple plugin that modifies our tree to see how difficult it is to update it and what things we need to expose on Zotero's end to support our plugin developers and the scite plugin was a good candidate for it.

This PR changes the scite plugin to work with the new Zotero HTML item tree. It is currently only available when building Zotero via its source, but we'll soon make it available via the Dev release channel (to get it, use the links from [Zotero Beta](https://www.zotero.org/support/dev_builds#zotero_beta) for your OS and replace channel=beta with channel=dev in the URL). Bellow I'll describe the changes that were necessary to make the plugin (or rather, item tree modifications) work with the new HTML tree. We'll later use some version of this in our transition guide.

### Zotero.ItemTreeView is gone
You can find the new tree interface at `chrome/content/zotero/itemTree.jsx`. It is imported for monkey-patching by calling `require('zotero/itemTree')`.

### `getCell() -> _getRowData()`
`getCell()` is replaced with `_getRowData()`. Instead of Zotero querying data for individual cells it now queries data for the whole row at once. `getCellProperties()` no longer exists.
Note that you can only monkey-patch the `_getRowData()` method on a live item tree object, the function does not exist on the prototype. I recommend awaiting the `Zotero.Schema.schemaUpdatePromise` promise before patching.

### Columns are injected via a `getColumns()` monkey-patch

With the XUL tree the columns are injected by overloading the `<treecols>` element. With the HTML tree you instead need to monkey-patch `getColumns()`. See `chrome/content/zotero/itemTreeColumns.jsx` for more info on available column properties. Note that this method must be patched on the ItemTree prototype, before it is initialized, otherwise your columns won't show up.

### Adjusting cell look

You may override `ItemTree.prototype._renderCell()` to alter the way your cells are rendered in the tree.

### Context menus

No changes are necessary. Context menu modifications should work as before.

--------

NOTE: We will be releasing the HTML tree on the Zotero Beta channel sometime soon. You should make sure that your plugin works with both stable and beta Zotero versions where one will have the old XUL tree and the new one will have the HTML tree. This PR makes it only work with the HTML tree.

P.S. Sorry, this isn't a very clean update. I was primarily looking to do this fast and to make sure we expose everything on Zotero's end.

### CODE REVIEW

**Comment by retorquere** [comment]
@adomasven is there a general description of what this PR changes? I'm looking through the patch, and the BBT code isn't directly analogous to this.

**Comment by dstillman** [comment]
There's a whole description above. Not sure what else you're looking for.

**Comment by retorquere** [comment]
My bad. I dove straight into the patch.

**Comment by retorquere** [comment]
Must I `require('zotero/itemTree')` before I can test for `typeof Zotero.ItemTreeView != "undefined"`?

**Comment by adomasven** [comment]
> Must I `require('zotero/itemTree')` before I can test for `typeof Zotero.ItemTreeView != "undefined"`?

You should not. That require will throw if running on a XUL tree zotero.

I think we should keep the discussion on this PR for the scite plugin devs since this is their repo. We'll answer any transition questions in your dev mailing list thread. If you want a discussion on github specific to BBT, tag me and Dan on an issue or PR on BBT repo.

**Comment by retorquere** [comment]
In `_renderCell`, must I always return a span with two subspans, with those classnames? or can I just return a single span with className `cell ${column.className} cell-text`?

**Comment by u-ashish** [comment]
Thanks @adomasven for getting this started, and to everyone for the discussions which helped clarify a lot of questions I had in this process.

I pushed a few changes to your fork / branch that:
- Fixes a few linter issues during the build
- Adds backwards compatibility so this can work with both the XUL or HTML tree rendering. Specifically, I make the patch strategy conditional based on whether `ItemTreeView` is defined, i.e. using `const usingXULTree = typeof Zotero.ItemTreeView !== 'undefined'`, which from what I read should be a reliable indicator.
- Maybe I am being dumb but it looked like I needed to keep the column names `zotero-items-column-*` for now for rendering to work in the old XUL version of the client, so I changed the columns name to that instead.
- In the old XUL version we used `col.id` but now we use `col.dataKey` so there is some duplication of the column definitions, but once we fully release the new version of Zotero and drop support for the XUL based rendering, I can easily clean this up in the future.

## Testing

I verified that this works with the following builds of Zotero on my local machine.

**5.0.96.3**
Screen Shot 2021-08-31 at 2 49 03 PM

**5.0.97-beta.43+c5d89f6d0**
Screen Shot 2021-08-31 at 3 06 53 PM

**Comment by u-ashish** [comment]
Oh, @adomasven I do have one question:

In the previous zotero version, when our API calls finished and the data was loaded, the cells would automatically update with the data (instead of relying on our loading animation).

With the new beta client, what is the best way to trigger the refresh on the rows / cells? I think right now it only refreshes if I e.g. sort a column or click on a row, but I assume I can do this programmatically so it isn't as confusing for users?

**Comment by dstillman** [comment]
See [this discussion](https://github.com/retorquere/zotero-better-bibtex/discussions/1904#discussioncomment-1249989) for the various options (basically `ZoteroPane.itemsView.refreshAndMaintainSelection()` or `Zotero.Notifier.trigger('refresh', 'item', [item ids])`).

**Comment by u-ashish** [comment]
Got it, thanks @dstillman, missed that part of the thread

**Comment by retorquere** [comment]
The description in the first message is not accurate anymore; at least the monkey-patch of `_getRowData` is not needed.

**Pull request merged**
